name: deploy-prod

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'

      - name: Build & Export
        run: |
          yarn install 
          yarn build

      - name: Deploy to S3 and Invalidate CloudFront
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-west-1
        run: |
          aws s3 sync ./dist s3://wafflestudio-seminar-2024-frontend-uzin-prod --delete # 
          aws cloudfront create-invalidation --distribution-id EGTKG2J0O5BRS --paths "/*" #
